### ISSUE TITLE
Not working correct with a.e. mcp23s17

### ISSUE THREAD

**Issue by mfulz** [JChristensen/tinySPI#1]
I've found some issue, which is not working correct:

in file https://github.com/JChristensen/tinySPI/blob/master/tinySPI.cpp 
it must be:
void tinySPI::begin(void)
{
USICR &= ~(_BV(USISIE) | _BV(USIOIE) | _BV(USIWM1));
USICR |= _BV(USIWM0) | _BV(USICS1) | _BV(USICLK);
SPI_DDR_PORT |= _BV(USCK_DD_PIN); //set the USCK pin as output
SPI_DDR_PORT &= _BV(DI_DD_PIN); //set the DI pin as input
SPI_DDR_PORT |= ~_BV(DO_DD_PIN); //set the DO pin as output
}

and in file https://github.com/JChristensen/tinySPI/blob/master/tinySPI.h
it must be:
# elif defined(**AVR_ATtiny45**) || defined(**AVR_ATtiny85**)
# define SPI_DDR_PORT DDRB
# define USCK_DD_PIN DDB2
# define DI_DD_PIN DDB1
# define DO_DD_PIN DDB0
# endif

WIth that it's working fine together with this class http://playground.arduino.cc/Main/MCP23S17
I've done some little modifications for it to work with the attiny85 and the above changes are needed for it.

**Comment by JChristensen** [comment]
In the first patch, to tinySPI.cpp, these lines are incorrect, neither sets a single bit as they should:

``` c++
SPI_DDR_PORT &= _BV(DI_DD_PIN); //set the DI pin as input
SPI_DDR_PORT |= ~_BV(DO_DD_PIN); //set the DO pin as output
```

The second patch exchanges the DO and DI pins, which does not match the pinout in the datasheet. There may be some confusion as DI is shared with MOSI and DO with MISO. MISO and MOSI are for ICSP. DI and DO are for the USI. That is counter-intuitive but that's the way it is.

I'd bet reversing the connections to DI and DO would have solved the problem.

**Comment by mfulz** [comment]
No it doesn't I've tried to reverse the cables and it didn't worked till I've changed your code.

**Comment by JChristensen** [comment]
I don't have an MCP23S17 so I can't test.
Have you tried the example sketch with a 595 shift register? Does that work for you?
What SPI modes does the MCP23S17 support? tinySPI only supports modes 0 and 1.
I stand by my previous comments regarding the patches. The DDR bits are not being correctly set, and the DO and DI pins are improperly interchanged.

**Comment by mfulz** [comment]
First: I'm quite new to all this (can programm though) and perhaps I'm wrong.
But I'm using this class for the MCP23S17: https://github.com/n0mjs710/MCP23S17/tree/master/MCP23S17
the SPI mode is 0 and inside this code I'm only seeing transfer calls and the PIN toggle for the SS pin (which I declared as pin 4 on the attiny).
I've done some patching for the MCP class: https://github.com/n0mjs710/MCP23S17/issues/2 and it was only working after the changes I've posted here.
I was confused about this, because as you say it's written different in the datasheet but it just wasn't working.
And yes you're example sketch with 595 is working though.

**Comment by JChristensen** [comment]
Sorry I cannot entertain this further without _either_ a [SSCCE](http://sscce.org/) that demonstrates the problem and does not involve hardware I don't have or mods to other libraries that allegedly fix the problem, _or_ a concise yet complete explanation of exactly what the alleged problem is. In other words, I don't want to be told the solution, I want to be told what the problem is.

The fix provided is demonstrably incorrect. Consider that the result of the following is to set all pins as outputs, except PB0 (the DI pin). Interestingly, with regard to just the USI pins, this is exactly what the library currently does.

``` c++
#define DI_DD_PIN DDB1              //incorrect because DI is actually PB0
#define DO_DD_PIN DDB0              //incorrect because DO is actually PB1
SPI_DDR_PORT &= _BV(DI_DD_PIN);     //if PORTB is in its default state (i.e. after reset),
                                    //this does nothing, but if DDB1 is on, leaves it on and
                                    //clears all other bits.
SPI_DDR_PORT |= ~_BV(DO_DD_PIN);    //sets all bits except DDB0. regardless of the initial
                                    //state or PORTB and the effect of the previous line,
                                    //this results in all pins being set as outputs, except
                                    //PB0, which is the actual DI pin.
```

Further, the first line below is also incorrect, the symbols must have the additional underscores in them. If they were intentionally removed, then the code between #elif and #endif will not be compiled. If this was a typo, then I have to wonder what other typos have been made.

``` c++
#elif defined(AVR_ATtiny45) || defined(AVR_ATtiny85)            //wrong
#elif defined(__AVR_ATtiny45__) || defined(__AVR_ATtiny85__)    //right
```

**Comment by mfulz** [comment]
Ok no problem I can understand you.
I'll try it with your unmodified library later on, provide you the code and you can test it, if you have the time.
For the second part:
"If this was a typo, then I have to wonder what other typos have been made."
Please don't be that offence, I just wanted to help not more. And it's not a typo I just forgot to use the code block and the underscores where removed....

**Comment by JChristensen** [comment]
No offense intended. (How could I know?)

**Comment by mfulz** [comment]
OMG sorry you've been right.
this here was really a typo in my code which was leading to expected behavior by mistake:

```
#define DI_DD_PIN DDB1              //incorrect because DI is actually PB0
#define DO_DD_PIN DDB0              //incorrect because DO is actually PB1
SPI_DDR_PORT &= _BV(DI_DD_PIN);     //if PORTB is in its default state (i.e. after reset),
                                    //this does nothing, but if DDB1 is on, leaves it on and
                                    //clears all other bits.
SPI_DDR_PORT |= ~_BV(DO_DD_PIN);    //sets all bits except DDB0. regardless of the initial
                                    //state or PORTB and the effect of the previous line,
                                    //this results in all pins being set as outputs, except
                                    //PB0, which is the actual DI pin.
```

But your comments pointed me to the solution. I've had to set my "SS" pin DDB4 as output before I'm using that one inside my modified MCP23S17 class.
So adding following line was working fine now:

```
#define SS_DD_PIN DDB4

void tinySPI::begin(void)
{
    USICR &= ~(_BV(USISIE) | _BV(USIOIE) | _BV(USIWM1));
    USICR |= _BV(USIWM0) | _BV(USICS1) | _BV(USICLK);
    SPI_DDR_PORT |= _BV(USCK_DD_PIN);   //set the USCK pin as output
    SPI_DDR_PORT |= _BV(DO_DD_PIN);     //set the DO pin as output
    SPI_DDR_PORT &= ~_BV(DI_DD_PIN);    //set the DI pin as input 
    SPI_DDR_PORT |= _BV(SS_DD_PIN);     //set the SS pin as output
}
```

But perhaps you can help me understanding why it is acting like that? Or even add these lines to your library. I don't know if they could have some negative effect.

Again sorry for it :)

**Comment by JChristensen** [comment]
No worries, glad you got it sorted out. Any pin can be used for slave select, it's up to the user. Setting SS to output mode does not belong in the library, it belongs in the user code. What if someone wanted to use a different pin for SS, or several SS pins for several SPI devices? I might just call pinMode() to set it to output mode, that might be a bit more straightforward.
