### ISSUE TITLE
ATTiny 85  sending data via RFM96

### ISSUE THREAD

**Issue by medida** [JChristensen/tinySPI#10]
Hi

I'm trying to get to grips with an ATtiny85 using this tinySPI to send data via an RFM96.

At the moment i have added the library and in the setup added the 
 SPI.setDataMode(SPI_MODE0);
  SPI.begin();

But as soon as it gets to the SPI.begin() - it stop responding.

This is a blank project at the moment as i'm slowly testing options.

Will this work on the ATtiny85 as i have read elsewhere that it soes not support Hardware SPI?

Thanks

**Comment by JChristensen** [comment]
Please refer to the [ATiny85 datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-2586-AVR-8-bit-Microcontroller-ATtiny25-ATtiny45-ATtiny85_Datasheet.pdf) and also the [Description](https://github.com/JChristensen/tinySPI#description) in the README file for this library.

Indeed the ATtiny85 does support hardware SPI. This library is specifically to allow use of its SPI (USI) hardware. 

The ATtiny85 USI hardware does have a couple limitations as compared to more sophisticated MCUs. Whether these would preclude its use with the RFM96, I cannot say as I have not looked into it.
