### ISSUE TITLE
Publish for the Arduino Library Manager

### ISSUE THREAD

**Issue by rlogiacco** [JChristensen/tinySPI#5]
it would be nice if you could add this library into the Arduino Library Manager: it only requires an additional file in your repository (I can provide that) and creating a request for addition.

**Comment by dontsovcmc** [comment]
And Platformio :)

**Comment by JChristensen** [comment]
Now in the Arduino Library Manager as of b00672347a08e26afc305d2ac727a4e5fefb9d5a
