### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bmuessig** [JChristensen/tinySPI#7]
This library is licensed under the terms of the GPL license. Why?
It's tiny, i.e. contains not much code at all. If I would be to write my own, licensed under a more permissive license such as BSD, it would have to look somewhat similar to match Arduino's style but you would probably call me out for plagarism. GPL for libraries is wrong anyways. There's LGPL for libraries, but in this case not GPL nor LGPL are the right choice. For this little code, having to open source one's own entire project is just mean. This library is the size of the typical StackOverflow "How do I get X working?" answer and is still forcing a non-permissive license onto one's entire project.
I am using GPL myself, but only when I know it would matter. If not, I always go for the New, 3-clause BSD license, since it allows me to make full use of the library, while naming the original author, but not having to open-source the entire code just to use a small USPI library.

Please reconsider your choice! Thanks.

**Comment by JChristensen** [comment]
It may not be a lot of code but you have no idea the hours and hours involved in poring over the datasheet, testing, benchmarking, measuring, optimizing, etc. Lock yourself in the lab and write your own from scratch with nothing but the datasheet, hardware and test equipment. Let us know how long that takes and I won't call you out for plagiarism.
